name: Pylint

on:
  push:
    branches:
    - main
    - 'releases/**'
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv sync                        # install dependencies
        source .venv/bin/activate      # use virtual environment
        pip install -e .               # make project importable
    - name: Analyzing the code with pylint
      run: |
        which python
        source .venv/bin/activate
        which python
        which pylint
        pylint --version
        echo "Testing python imports"
        python -c "from esm.sdk import client"
        echo "Starting pylint analysis..."
        pylint $(git ls-files '*.py')
